from fastapi import FastAPI, Request, Response, Cookie, Form, HTTPException
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from fastapi.responses import JSONResponse, PlainTextResponse, RedirectResponse

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello, World!"}


@app.get("/hello/{name}")
async def say_hello(name: str):
    return {"message": f"Hello {name}"}


@app.get("/greet/{name}")
async def greet(name: str):
    return {"message": f"Hello, {name}!"}


@app.get("/search")
async def search(query: str):
    return {"message": f"You searched for: {query}"}


@app.get("/json")
async def json_info():
    return {
        "name": "Assistant",
        "age": 1,
        "hobbies": ["coding", "reading", "music"]
    }


@app.get("/file")
async def send_file():
    content = "This is a sample text file generated by FastAPI.\nEnjoy!"
    headers = {"Content-Disposition": "attachment; filename=sample.txt"}
    return PlainTextResponse(content=content, headers=headers)


@app.get("/redirect")
async def redirect_to_root():
    return RedirectResponse(url="/")


@app.get("/headers")
async def get_headers(request: Request):
    return {k: v for k, v in request.headers.items()}


@app.get("/set-cookie")
async def set_cookie():
    response = JSONResponse({"message": "Cookie set"})
    response.set_cookie(key="username", value="your_name", httponly=True)
    return response


@app.get("/get-cookie")
async def get_cookie(username: Optional[str] = Cookie(default=None)):
    return {"username": username}


@app.post("/login")
async def login(username: str = Form(...), password: str = Form(...)):
    return {"message": f"Welcome, {username}!"}


class RegisterRequest(BaseModel):
    username: str
    email: EmailStr
    password: str


@app.post("/register")
async def register(payload: RegisterRequest):
    return {"message": f"User {payload.username} registered successfully!"}


class User(BaseModel):
    id: int
    username: str
    email: EmailStr
    password: str


FAKE_USERS: List[User] = [
    User(id=1, username="alice", email="alice@example.com", password="secret1"),
    User(id=2, username="bob", email="bob@example.com", password="secret2"),
    User(id=3, username="carol", email="carol@example.com", password="secret3"),
]


@app.get("/users", response_model=List[User])
async def list_users():
    return FAKE_USERS


@app.get("/users/{id}", response_model=User)
async def get_user(id: int):
    for user in FAKE_USERS:
        if user.id == id:
            return user
    raise HTTPException(status_code=404, detail="User not found")
